### ISSUE TITLE
When "Brute force" protection activated, captcha already is "incorrect"

### ISSUE THREAD

**Issue by ghost** [yii2tech/authlog#1]
![screenshot2016-03-12_03 10 38](https://cloud.githubusercontent.com/assets/16696651/13720100/92cb7750-e800-11e5-9f55-e1cc69ac8104.png)

**Comment by ghost** [comment]
Pavel - you can write me in russian rumatakira dog yahoo dot com. Thank you.

**Comment by klimov-paul** [comment]
> When "Brute force" protection activated, captcha already is "incorrect"

This is expected: once it comes to the CAPTCHA verification an error message is added to the corresponding attribute. Without it there is no way to enforce CAPTCHA entering.

Still I think I understand your complain. Need to investigate if there is another solution.

**Comment by ghost** [comment]
For my purposes - it's ok. Attract more attention to the field. Maybe perfectionism - is the evil, so - never mind ;)

**Comment by klimov-paul** [comment]
I have reviewed the code and could not find good solution to bypass the right away validation error.
In theory some virtual attribute name can be used to place the first error for the robot check, so validation will fail, while verify code field will show no error. But I can see no good way to implement this.

If anyone comes to a good solution for the case - let me know.

**Comment by ghost** [comment]
May be like this - set the flag does captcha called first time, and redefine error message to empty user message.
